# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

stages:
- stage: Build
  condition: |
    and(
      not(contains(variables['Build.SourceVersionMessage'], '[skip ci]')),
      not(contains(variables['Build.SourceVersionMessage'], '[ci skip]'))
      not(contains(variables['Build.SourceVersionMessage'], '[skip azure]'))
      not(contains(variables['Build.SourceVersionMessage'], '[skip azp]'))
      not(contains(variables['Build.SourceVersionMessage'], '***NO_CI***'))
    )
  jobs:
    - template: ./.azure-pipelines/azure-pipelines-linux.yml
    - template: ./.azure-pipelines/azure-pipelines-osx.yml
    - template: ./.azure-pipelines/azure-pipelines-win.yml